language: php

sudo: false

php:
  - 7.0.5

git:
  submodules: false
  depth: 10

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --optimize-autoloader --prefer-source --no-interaction

#script:
#  - ./vendor/bin/phpcbf --standard=PSR2 ./src
#  - ./vendor/bin/phpcs --standard=PSR2 ./src

notifications:
  email: false